# Generated by Django 3.2.22 on 2024-01-02 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalstatushistory',
            name='date_changed',
        ),
        migrations.AddField(
            model_name='internalstatushistory',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
