# Generated by Django 3.2.22 on 2024-01-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240102_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternalStatusHistory',
        ),
    ]
