# Generated by Django 3.2.22 on 2024-01-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_internalstatushistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternalStatusHistory',
        ),
    ]
