# Generated by Django 3.2.22 on 2024-01-04 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_auto_20240103_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(unique=True)),
                ('department', models.CharField(choices=[('Account', 'Account'), ('CG', 'CG'), ('Comp', 'Comp'), ('DMP', 'DMP'), ('Editor', 'Editor'), ('HR', 'HR'), ('IT', 'IT'), ('MGFX', 'MGFX'), ('Matchmove', 'Matchmove'), ('Paint', 'Paint'), ('Pipeline', 'Pipeline'), ('Production', 'Production'), ('Roto', 'Roto')], max_length=100)),
                ('designation', models.CharField(choices=[('Intern', 'Intern'), ('Trainee', 'Trainee'), ('Jr. Artist', 'Jr. Artist'), ('Sr. Artist', 'Sr. Artist'), ('TD', 'TD'), ('Data IO', 'Data IO'), ('System Admin', 'System Admin'), ('Coordinator', 'Coordinator'), ('Team Lead', 'Team Lead'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
