# Generated by Django 3.2.22 on 2024-02-09 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_adminextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='approve',
            name='version',
            field=models.CharField(blank=True, default='V0000', max_length=5, null=True, verbose_name='Version No.'),
        ),
        migrations.AddField(
            model_name='review',
            name='version',
            field=models.CharField(blank=True, default='V0000', max_length=5, null=True, verbose_name='Version No.'),
        ),
        migrations.AddField(
            model_name='shot2',
            name='dep1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shot2',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shot2',
            name='depnote',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Department Note'),
        ),
        migrations.AddField(
            model_name='shot2',
            name='recdepnote',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Received Department Note'),
        ),
        migrations.AlterField(
            model_name='adminextra',
            name='department',
            field=models.CharField(choices=[('CG', 'CG'), ('Comp', 'Comp'), ('DMP', 'DMP'), ('Editor', 'Editor'), ('IT', 'IT'), ('MGFX', 'MGFX'), ('Management', 'Management'), ('Matchmove', 'Matchmove'), ('Paint', 'Paint'), ('Pipeline', 'Pipeline'), ('Production', 'Production'), ('Roto', 'Roto')], max_length=100),
        ),
        migrations.AlterField(
            model_name='adminextra',
            name='designation',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Trainee', 'Trainee'), ('Jr. Artist', 'Jr. Artist'), ('Sr. Artist', 'Sr. Artist'), ('TD', 'TD'), ('Data IO', 'Data IO'), ('System Admin', 'System Admin'), ('Coordinator', 'Coordinator'), ('Team Lead', 'Team Lead'), ('Supervisor', 'Supervisor'), ('Production Manager', 'Production Manager'), ('VFX Producer', 'VFX Producer'), ('VFX Head', 'VFX Head')], max_length=100),
        ),
        migrations.AlterField(
            model_name='issuedshot',
            name='shot_version',
            field=models.CharField(blank=True, default='V000', max_length=255, null=True, verbose_name='Version No.'),
        ),
        migrations.AlterField(
            model_name='sendfeedback',
            name='shot_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Version No.'),
        ),
        migrations.AlterField(
            model_name='shot2',
            name='shot_version',
            field=models.CharField(blank=True, default='V000', max_length=5, null=True, verbose_name='Version No.'),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='department',
            field=models.CharField(choices=[('CG', 'CG'), ('Comp', 'Comp'), ('DMP', 'DMP'), ('Editor', 'Editor'), ('IT', 'IT'), ('MGFX', 'MGFX'), ('Management', 'Management'), ('Matchmove', 'Matchmove'), ('Paint', 'Paint'), ('Pipeline', 'Pipeline'), ('Production', 'Production'), ('Roto', 'Roto')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='designation',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Trainee', 'Trainee'), ('Jr. Artist', 'Jr. Artist'), ('Sr. Artist', 'Sr. Artist'), ('TD', 'TD'), ('Data IO', 'Data IO'), ('System Admin', 'System Admin'), ('Coordinator', 'Coordinator'), ('Team Lead', 'Team Lead'), ('Supervisor', 'Supervisor'), ('Production Manager', 'Production Manager'), ('VFX Producer', 'VFX Producer'), ('VFX Head', 'VFX Head')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='reporting',
            field=models.CharField(choices=[('Mr. Riaz Patel (VFX Head)', 'Mr. Riaz Patel (VFX Head)'), ('Mr. Abhishek Kulkarni (Production Manager)', 'Mr. Abhishek Kulkarni (Production Manager)'), ('Mr. Swapnil Kharche (VFX Producer)', 'Mr. Swapnil Kharche (VFX Producer)'), ('Mr. Kunal Salunkhe', 'Mr. Kunal Salunkhe'), ('Mr. Ranjan Sharma', 'Mr. Ranjan Sharma'), ('Mr. Swapnil Zambare', 'Mr. Swapnil Zambare'), ('Mr. Chinmay Deshpande', 'Mr. Chinmay Deshpande'), ('Mr. Akshay Yadav', 'Mr. Akshay Yadav')], max_length=100),
        ),
        migrations.CreateModel(
            name='ShotDepNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depnotes', models.JSONField(blank=True, default=list, null=True, verbose_name='Department Notes')),
                ('recdepnotes', models.JSONField(blank=True, default=dict, null=True, verbose_name='Received Department Notes')),
                ('recdates', models.DateField(blank=True, null=True, verbose_name='Date Received')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_notes', to='user.shot2')),
            ],
        ),
    ]
