# Generated by Django 3.2.22 on 2024-01-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20240104_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='approve',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
