# Generated by Django 3.2.22 on 2024-01-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_approve_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminextra',
            name='designation',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Trainee', 'Trainee'), ('Jr. Artist', 'Jr. Artist'), ('Sr. Artist', 'Sr. Artist'), ('TD', 'TD'), ('Data IO', 'Data IO'), ('System Admin', 'System Admin'), ('Coordinator', 'Coordinator'), ('Team Lead', 'Team Lead'), ('Supervisor', 'Supervisor'), ('Production Manager', 'Production Manager'), ('VFX Producer', 'VFX Producer'), ('VFX Head', 'VFX Head')], max_length=100),
        ),
        migrations.AlterField(
            model_name='issuedshot',
            name='shot_version',
            field=models.CharField(blank=True, default='V0000', max_length=255, null=True, verbose_name='Version No.'),
        ),
        migrations.AlterField(
            model_name='shot2',
            name='shot_version',
            field=models.CharField(blank=True, default='V0000', max_length=5, null=True, verbose_name='Version No.'),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='designation',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Trainee', 'Trainee'), ('Jr. Artist', 'Jr. Artist'), ('Sr. Artist', 'Sr. Artist'), ('TD', 'TD'), ('Data IO', 'Data IO'), ('System Admin', 'System Admin'), ('Coordinator', 'Coordinator'), ('Team Lead', 'Team Lead'), ('Supervisor', 'Supervisor'), ('Production Manager', 'Production Manager'), ('VFX Producer', 'VFX Producer'), ('VFX Head', 'VFX Head')], max_length=100),
        ),
    ]
