# Generated by Django 3.2.22 on 2024-01-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_sendfeedback_shot_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='version',
            field=models.CharField(blank=True, default='V0000', max_length=5, null=True, verbose_name='Version No.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='version',
            field=models.CharField(blank=True, default='V0000', max_length=5, null=True, verbose_name='Version No.'),
        ),
    ]
