# Generated by Django 3.2.22 on 2024-01-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20240108_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot2',
            name='depnote',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Department Note'),
        ),
    ]
