# Generated by Django 3.2.22 on 2024-01-17 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_shot2_depnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotDepNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depnote', models.CharField(blank=True, max_length=255, null=True, verbose_name='Department Note')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_notes', to='user.shot2')),
            ],
        ),
    ]
