# Generated by Django 3.2.22 on 2024-01-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_shotdepnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shotdepnote',
            name='depnote',
        ),
        migrations.AddField(
            model_name='shotdepnote',
            name='depnotes',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Department Notes'),
        ),
    ]
