# Generated by Django 3.2.22 on 2024-01-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20240117_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot2',
            name='recdepnote',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Received Department Note'),
        ),
        migrations.AddField(
            model_name='shotdepnote',
            name='recdepnotes',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Received Department Notes'),
        ),
    ]
