# Generated by Django 3.2.22 on 2024-02-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20240117_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot2',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shotdepnote',
            name='recdates',
            field=models.DateField(blank=True, null=True, verbose_name='Date Received'),
        ),
        migrations.AlterField(
            model_name='issuedshot',
            name='shot_version',
            field=models.CharField(blank=True, default='V000', max_length=255, null=True, verbose_name='Version No.'),
        ),
        migrations.AlterField(
            model_name='shot2',
            name='shot_version',
            field=models.CharField(blank=True, default='V000', max_length=5, null=True, verbose_name='Version No.'),
        ),
        migrations.AlterField(
            model_name='shotdepnote',
            name='recdepnotes',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Received Department Notes'),
        ),
    ]
