# Generated by Django 3.2.22 on 2024-01-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20240117_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot2',
            name='wipnote',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='WIP Note'),
        ),
    ]
