# Generated by Django 3.2.22 on 2024-01-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_shot2_wipnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotdepnote',
            name='wipnotes',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='WIP Notes'),
        ),
    ]
