# Generated by Django 3.2.22 on 2024-01-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_shotdepnote_wipnotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shot2',
            name='wipnote',
        ),
        migrations.RemoveField(
            model_name='shotdepnote',
            name='wipnotes',
        ),
    ]
