# Generated by Django 3.2.22 on 2024-01-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20240130_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotdepnote',
            name='recdepnotes',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Received Department Notes'),
        ),
    ]
