# Generated by Django 3.2.22 on 2024-01-31 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_shotdepnote_recdepnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotdepnote',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Added'),
            preserve_default=False,
        ),
    ]
