# Generated by Django 3.2.22 on 2024-01-31 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_shotdepnote_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shotdepnote',
            name='date_added',
        ),
    ]
