# Generated by Django 3.2.22 on 2024-01-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_remove_shotdepnote_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotdepnote',
            name='recdates',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
