# Generated by Django 3.2.22 on 2024-02-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20240131_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot2',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
