# Generated by Django 3.2.22 on 2024-02-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_remove_shot2_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot2',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
