# Generated by Django 3.2.22 on 2024-02-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_shot2_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot2',
            name='dep1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
